services:
  postgres:
    image: postgres:14.6
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password # Default password, change it
      POSTGRES_DB: dbname
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: aiker@gaga.com
      PGADMIN_DEFAULT_PASSWORD: admin # Default password, change it
    restart: unless-stopped

volumes:
  postgres-data: